const sessions = {
  '力量 A': { summary:'下肢、推与核心。约 35-45 分钟，动作稳定优先。', exercises:[['自重深蹲','3 组 × 10-15 次','YaXPRqUwItQ'],['高位俯卧撑','3 组 × 8-12 次','0GsVJsS6474'],['臀桥','3 组 × 12-20 次','wPM8icPu6H8'],['扶椅后撤箭步蹲','2-3 组 × 每侧 8-10 次','xrPteyQLGAo'],['死虫式','3 组 × 每侧 6-10 次','I5xbsA71v1A'],['侧桥','2 组 × 每侧 15-30 秒','K2VljzCC16g']] },
  '力量 B': { summary:'臀腿、肩胛稳定与核心。约 30-40 分钟，动作稳定优先。', exercises:[['靠墙静蹲','3 组 × 35-60 秒','y-wV4Venusw'],['单腿臀桥','3 组 × 每侧 8-12 次','wPM8icPu6H8'],['高位俯卧撑','3 组 × 8-12 次','0GsVJsS6474'],['墙面滑手','3 组 × 8-12 次','CiM-s8I5dl8'],['俯卧 Y-T 抬臂','各 2 组 × 6-10 次','CiM-s8I5dl8'],['平板支撑','3 组 × 20-40 秒','pSHjTRCQxIw']] },
  '跑走耐力': { summary:'保持能说完整句子的强度；不适时改为快走。', exercises:[['热身快走','8 分钟','ml6cT4AZdqI'],['跑走交替','跑 2 分钟 + 走 2 分钟，7-8 轮','9L2b2khySLE'],['放松慢走','5 分钟','ml6cT4AZdqI'],['小腿拉伸','每侧 2 组 × 30 秒','YQmpO9VT2X4']] },
  '恢复日': { summary:'今天的份额是恢复。轻松完成即可，不追求训练感。', exercises:[['轻松快走','20-30 分钟','ml6cT4AZdqI'],['踝关节活动','每侧 1 分钟','IikP_teeLkI'],['墙面肩胛俯卧撑','2 组 × 10-15 次','g9d3B9J1Y9U'],['呼吸放松','3 分钟','aNXKjGFUlMs']] }
};
const repairs=[['单脚站立','每侧 2 组 × 30 秒','IikP_teeLkI'],['慢速提踵','3 组 × 12-20 次','YQmpO9VT2X4'],['墙面肩胛俯卧撑','2 组 × 10-15 次','g9d3B9J1Y9U'],['墙面滑手','2 组 × 8-12 次','CiM-s8I5dl8']];
const guides={
  '自重深蹲':{images:['assets/guides/bodyweight-squat-ai.png'],steps:['双脚与髋同宽，脚尖自然微外，胸口保持打开。','臀部先向后坐，膝盖沿脚尖方向移动；下到可稳定控制的深度。','脚掌均匀发力站起，不要用膝盖内扣或借反弹起身。']},
  '高位俯卧撑':{images:['assets/guides/incline-pushup-ai.png'],steps:['双手放在稳定的高支撑面，身体从头到脚跟成一条直线。','吸气下降，肘部向后约 30-45 度，不耸肩。','呼气推回；出现不稳、锐痛或麻木时立即停止。']},
  '臀桥':{images:['assets/guides/bridge-start.svg','assets/guides/bridge-up.svg'],steps:['仰卧屈膝，脚跟在膝盖正下方附近，腰背自然贴地。','用脚跟轻推地面，收紧臀部将髋抬到躯干与大腿接近直线。','顶部停一秒后慢慢下放；不要靠过度挺腰抬高。']},
  '扶椅后撤箭步蹲':{images:['assets/guides/lunge-start.svg','assets/guides/lunge-down.svg'],steps:['轻扶稳固椅背，先站稳，后脚向后迈一小步。','垂直下沉，前膝对准第二脚趾方向，重心保持在两脚之间。','以前脚推地回到站姿；脚踝不稳就缩短步幅或改靠墙静蹲。']},
  '死虫式':{images:['assets/guides/dead-bug-ai.png'],steps:['仰卧，髋膝 90 度，双臂伸向天花板，轻轻收紧腹部。','缓慢伸远一侧腿和对侧手臂：图中是左臂向后、右腿向前。','呼气回到起始位，再换边；范围小也没关系。']},
  '侧桥':{images:['assets/guides/side-plank.png'],steps:['前臂放在肩正下方，双腿伸直或屈膝降低难度。','抬起髋部，让头、肩、髋、踝尽量连成直线。','保持呼吸，髋下沉或肩不适时结束该组。']},
  '靠墙静蹲':{images:['assets/guides/wall-sit-ai.png'],steps:['背部贴墙，双脚向前迈出约半步到一步。','慢慢下滑到无膝痛且能稳定的角度，膝盖对准脚尖。','全脚掌着地、持续呼吸；膝痛或脚踝不适就提高角度。']},
  '单腿臀桥':{images:['assets/guides/single-leg-bridge-ai.png'],steps:['先完成双腿臀桥姿势，再将一侧脚轻轻抬离地面。','支撑脚跟推地抬髋，骨盆尽量保持水平。','动作变形时改回双腿臀桥，不用追求抬得很高。']},
  '墙面滑手':{images:['assets/guides/wall-slide-ai.png'],steps:['背靠墙或面向墙站立，肋骨轻轻收住，肩颈放松。','双手沿墙缓慢上滑，只到肩部稳定、无痛的范围。','下滑时保持肩胛平稳；卡住、不稳或疼痛就停止。']},
  '俯卧 Y-T 抬臂':{images:['assets/guides/prone-yt-ai.png'],steps:['俯卧，额头轻贴毛巾，先把肩膀远离耳朵。','分别以 Y 和 T 形缓慢抬臂，幅度小、停一秒即可。','不要甩手或耸肩；出现不稳感时跳过。']},
  '平板支撑':{images:['assets/guides/forearm-plank-ai.png'],steps:['前臂在肩正下方，双腿向后伸直，脚尖支地。','收紧臀腹，让身体保持长直线，不塌腰也不抬臀。','正常呼吸；姿势变形前结束，比硬撑更有效。']},
  '热身快走':{images:['assets/guides/brisk-walk-ai.png'],steps:['前 2 分钟用舒适步速，脚掌轻柔落地。','逐步加快到身体微热但仍能完整说话的速度。','若脚踝疼痛或不稳，改为更慢速度并缩短时间。']},
  '跑走交替':{images:['assets/guides/run-walk-ai.png'],steps:['先走 8 分钟热身，再用轻松跑开始每组。','跑段保持能控制的步频，不冲刺；走段让呼吸恢复。','脚踝出现疼痛、肿胀或不稳时当次改为全程快走。']},
  '放松慢走':{images:['assets/guides/brisk-walk-ai.png'],steps:['训练后立刻切换为轻松步速。','让呼吸逐渐平稳，双肩放松。','至少走 5 分钟，再进行轻柔拉伸。']},
  '小腿拉伸':{images:['assets/guides/calf-stretch-ai.png'],steps:['双手扶墙，一脚在后，后脚跟踩实地面。','后膝伸直时拉腓肠肌；微屈后膝时拉比目鱼肌。','保持轻微牵拉感，不弹震，也不要忍痛。']},
  '轻松快走':{images:['assets/guides/brisk-walk-ai.png'],steps:['选择平坦路线，步速以能轻松交谈为准。','脚步落地保持平稳，避免急转和坡度冲刺。','脚踝不适就提前结束，不把恢复日练成高强度日。']},
  '踝关节活动':{images:['assets/guides/ankle-circle.svg'],steps:['坐姿或扶墙站立，缓慢画圈活动脚踝。','分别做脚尖上勾、下压和内外转，幅度以舒适为准。','扭伤旧处若出现刺痛或肿胀，不要继续活动。']},
  '墙面肩胛俯卧撑':{images:['assets/guides/wall-scapular-push-ai.png'],steps:['双手撑墙，手臂伸直，身体保持稳定。','不屈肘，只让肩胛轻轻靠近再推远。','动作小且慢，出现任何不稳感都应停止。']},
  '呼吸放松':{images:['assets/guides/diaphragmatic-breathing-ai.png'],steps:['舒适躺下或坐直，一手放在腹部。','缓慢吸气让腹部轻轻鼓起，呼气比吸气稍长。','连续做 3 分钟，不憋气也不刻意用力。']},
  '单脚站立':{images:['assets/guides/single-leg-stand-ai.png'],steps:['站在墙边或椅旁，先双脚稳定后抬起一只脚。','支撑脚三点均匀着地，视线看前方。','脚踝摇晃明显时可轻触墙面，不必强行闭眼。']},
  '慢速提踵':{images:['assets/guides/slow-calf-raise-ai.png'],steps:['扶墙站稳，双脚平行，重心均匀落在前脚掌与脚跟。','缓慢抬起脚跟至最高点，停一秒。','用 2-3 秒慢慢放下；脚踝痛就减小幅度。']}
};
const $=selector=>document.querySelector(selector);
function localDateKey(date=new Date()){const y=date.getFullYear(),m=String(date.getMonth()+1).padStart(2,'0'),d=String(date.getDate()).padStart(2,'0');return `${y}-${m}-${d}`;}
const today=localDateKey();
let state=JSON.parse(localStorage.getItem('train-well-state')||'{}');
state.completedSessions=Array.isArray(state.completedSessions)?state.completedSessions:[];
state.setChecks=state.setChecks||{};
state.restedExercises=state.restedExercises||{};
state.cappedExercises=state.cappedExercises||{};
state.restDays=Array.isArray(state.restDays)?state.restDays:[];
state.readiness=state.readiness||'normal';
let calendarCursor=new Date(new Date().getFullYear(),new Date().getMonth(),1);
function save(){localStorage.setItem('train-well-state',JSON.stringify(state));}
function latestStrength(){return [...state.completedSessions].reverse().find(item=>item.session==='力量 A'||item.session==='力量 B');}
function recommendedSession(){const last=latestStrength();return last?.session==='力量 A'?'力量 B':last?.session==='力量 B'?'力量 A':'力量 A';}
function prepareToday(){if(state.planDate===today)return;state.session=recommendedSession();state.planDate=today;save();}
function typeLabel(session){return session==='力量 A'?'A':session==='力量 B'?'B':session==='跑走耐力'?'跑':'修';}
function motionType(name){if(/深蹲|箭步|静蹲/.test(name))return 'squat';if(/俯卧撑|滑手|Y-T/.test(name))return 'push';if(/臀桥/.test(name))return 'bridge';if(/跑|走|踵|踝|站立/.test(name))return 'walk';return 'core';}
function setCount(dose){const match=dose.match(/(\d+)(?:-\d+)?\s*组/);return match?Number(match[1]):1;}
function setKey(name){return `${today}|${state.session}|${name}`;}
function checkedSets(name){return state.setChecks[setKey(name)]||[];}
function restParts(name){if(/深蹲|箭步|静蹲/.test(name))return ['大腿或臀部','膝盖','脚踝'];if(/俯卧撑/.test(name))return ['胸臂','肩膀','手腕'];if(/臀桥/.test(name))return ['臀部','后侧大腿','腰部'];if(/死虫|侧桥|平板/.test(name))return ['腹部','腰部','肩部'];if(/滑手|Y-T|肩胛/.test(name))return ['肩胛','肩膀','颈部'];if(/提踵|小腿|踝|单脚/.test(name))return ['小腿','脚踝','足部'];if(/跑|走/.test(name))return ['呼吸恢复','膝盖','脚踝或足部'];if(/呼吸/.test(name))return ['呼吸节奏','胸口不适','头晕'];return ['目标肌肉','关节','整体疲劳'];}
function restButton(name){return `<button class="set-rest" data-rest-exercise="${name}">休息</button>`;}
function baseFeedbackProfile(name){if(/深蹲|箭步|静蹲/.test(name))return {context:'关注腿部用力、膝盖与脚踝的感受。',options:[['腿部发紧','大腿或臀部紧绷，但没有关节痛','休息 60-90 秒。下一组减少 2-4 次或缩短下蹲幅度；后撤箭步蹲仍紧时改为 2 组即可。'],['膝踝不适','膝盖、脚踝刺痛或站不稳','停止该动作，改为无痛范围的轻松走动或结束下肢训练；症状持续、肿胀或影响走路时咨询专业人士。']]};if(/俯卧撑/.test(name))return {context:'关注胸臂疲劳，以及肩膀和手腕的承受感。',options:[['胸臂疲劳','胸、三头肌发热或发紧','休息 60-90 秒；下一组降低次数或提高支撑面，不必补足原计划。'],['肩腕不适','肩前侧或手腕疼痛、卡住','停止该动作；可改为墙面肩胛俯卧撑。疼痛持续或影响日常活动时咨询专业人士。']]};if(/臀桥/.test(name))return {context:'臀部发力应更明显，腰部不应成为主要压力点。',options:[['臀腿疲劳','臀部或后侧大腿发紧','休息 60 秒，下一组减少次数或改回双腿臀桥，保持动作范围可控。'],['腰部不适','腰部顶住、疼痛或代偿明显','停止该动作，降低抬髋高度；当次不要继续加量，持续不适时咨询专业人士。']]};if(/死虫|侧桥|平板/.test(name))return {context:'核心动作以稳定躯干为先，不靠憋气或硬撑。',options:[['腹部疲劳','腹部发紧、发热但姿势仍稳定','休息 45-60 秒，下一组缩短时间或减小手脚伸展范围。'],['腰肩不适','腰部拱起、肩部顶住或疼痛','停止该动作；死虫式缩小范围，桥式动作可改屈膝版本。持续不适时咨询专业人士。']]};if(/滑手|Y-T|肩胛/.test(name))return {context:'肩胛控制应平稳，颈部不应代偿用力。',options:[['肩胛疲劳','肩胛周围发酸、轻微疲劳','休息 45-60 秒，下一组减小抬举幅度或次数。'],['肩颈不适','肩部卡住、刺痛或颈部紧张明显','停止该动作，放松后仅在无痛范围活动；症状持续时咨询专业人士。']]};if(/提踵|小腿|踝|单脚/.test(name))return {context:'关注小腿疲劳与脚踝稳定，不追求极限幅度。',options:[['小腿疲劳','小腿酸胀或紧绷','休息 45-60 秒，下一组减少次数或幅度，慢慢下放。'],['脚踝不适','疼痛、肿胀或明显摇晃','停止该动作，避免继续单脚负重；症状持续或加重时咨询专业人士。']]};if(/跑|走/.test(name))return {context:'跑走训练先看呼吸、步态和下肢是否稳定。',options:[['呼吸偏急','无法完整说一句话','降低为快走，直到呼吸恢复；下一轮缩短跑段或减少轮数。'],['下肢不适','膝、踝、足部疼痛或步态不稳','当次改为轻松走或结束训练；肿胀、持续疼痛或影响走路时咨询专业人士。']]};if(/呼吸/.test(name))return {context:'呼吸放松应舒适、自然，不应憋气或头晕。',options:[['难以放松','呼气不顺或身体紧绷','缩短到 1 分钟，恢复自然呼吸，不必刻意深吸。'],['头晕不适','头晕、胸闷或不舒服','停止练习，坐下或侧卧休息；症状持续或严重时寻求专业帮助。']]};return {context:'根据动作控制感与身体反应决定下一步。',options:[['局部疲劳','目标肌肉发紧但没有疼痛','休息 45-60 秒，下一组减少次数或幅度。'],['疼痛或不稳','刺痛、麻木、无力或失去控制','停止该动作；症状持续或影响日常活动时咨询专业人士。']]};}
function feedbackProfile(name){const profile=baseFeedbackProfile(name);const followUp=/深蹲|箭步|静蹲/.test(name)?['左右差异','单侧明显更累或站姿偏向一边','下一组从较弱侧开始，左右两边都按较弱侧次数完成；仍差异明显就结束该动作。']:/俯卧撑/.test(name)?['手臂先力竭','手臂先撑不住，胸部发力感不足','下一组提高支撑面并减少次数，身体保持直线；不必硬撑完成原次数。']:/臀桥/.test(name)?['后侧大腿抢力','大腿后侧比臀部更先紧绷','把脚跟略靠近臀部，降低抬髋高度；下一组减少次数。']:/死虫|侧桥|平板/.test(name)?['呼吸憋住','为了保持姿势而不自觉憋气','结束当前组，恢复自然呼吸；下一组缩短时间或减小范围。']:/滑手|Y-T|肩胛/.test(name)?['颈部代偿','脖子或斜方肌比肩胛更紧','降低手臂高度，先放松肩膀；下一组只做无颈部紧张的范围。']:/提踵|小腿|踝|单脚/.test(name)?['抽筋趋势','小腿开始跳动或接近抽筋','停止该组，轻柔活动脚踝并补水；当天不要继续增加提踵或跑量。']:/跑|走/.test(name)?['步伐变重','落地变重、步态开始散乱','当次改为轻松走，缩短下一跑段或提前结束训练。']:/呼吸/.test(name)?['呼吸过深','越做越紧或出现轻微头晕','恢复平常呼吸，不要强行深吸；不适持续则停止练习。']:['呼吸乱了','动作时难以保持自然呼吸','休息 45-60 秒，下一组减小次数或幅度，先恢复可控呼吸。'];profile.options.push(followUp);return profile;}
function feedbackButton(name,completed){return `<button class="set-feedback" data-feedback-exercise="${name}" data-feedback-sets="${completed}" aria-label="${name}状态反馈">状态反馈</button>`;}
function setButtons(name,dose){const checked=checkedSets(name),count=setCount(dose),single=count===1,key=setKey(name),rested=state.restedExercises[key],capped=state.cappedExercises[key],allDone=checked.length===count,next=Array.from({length:count},(_,i)=>i).find(i=>!checked.includes(i)),status=rested?`${rested}未恢复，今日休息`:capped?'已达上限，今天不再增加':allDone?'本动作已完成':single?'完成后记录本动作':'完成一组后自动进入下一组',summary=rested?'本动作休息':capped?'已达上限':single?(allDone?'已完成':'待完成'):`${checked.length} / ${count} 组`;return `<div class="set-summary"><strong class="${capped?'at-limit':''}">${summary}</strong><span class="${allDone?'all-done':''}">${status}</span></div>${single?'':`<div class="set-bar ${capped?'at-limit':''}" aria-label="已完成 ${checked.length} / ${count} 组"><i style="width:${checked.length/count*100}%"></i></div>`}<div class="set-checks">${rested?`<button class="set-undo" data-resume-exercise="${name}">恢复动作</button>`:capped?`<button class="set-undo" data-resume-cap="${name}">恢复进度</button>`:allDone?'<button class="set-complete" disabled>✓ 本动作完成</button>':`<button class="set-next" data-set-name="${name}" data-set-index="${next}">${single?'完成本动作':`完成第 ${next+1} 组`}</button>`}${feedbackButton(name,checked.length)}${rested||capped?'':restButton(name)}${checked.map(index=>`<button class="set-undo" data-set-name="${name}" data-set-index="${index}">${single?'撤销完成':`第 ${index+1} 组 ✓`}</button>`).join('')}</div>`;}
function checkReminder(){if(!state.reminder||!('Notification'in window)||Notification.permission!=='granted')return;const [hour,minute]=state.reminder.split(':').map(Number),now=new Date(),due=new Date();due.setHours(hour,minute,0,0);const key=`train-well-reminded-${today}`;if(now>=due&&!localStorage.getItem(key)){new Notification('今天的训练份额',{body:`${state.session}：${sessions[state.session].summary}`,icon:'icon.svg'});localStorage.setItem(key,'1');}}
function renderCalendar(){const year=calendarCursor.getFullYear(),month=calendarCursor.getMonth(),first=new Date(year,month,1),offset=(first.getDay()+6)%7,days=new Date(year,month+1,0).getDate();$('#calendar-title').textContent=new Intl.DateTimeFormat('zh-CN',{year:'numeric',month:'long'}).format(first);let cells=Array(offset).fill('<span class="calendar-day empty"></span>');for(let day=1;day<=days;day++){const key=localDateKey(new Date(year,month,day)),completed=state.completedSessions.find(item=>item.date===key),record=completed||state.restDays.includes(key)?completed||{session:'恢复日'}:null,isToday=key===today;cells.push(`<span class="calendar-day ${record?'has-record':''} ${isToday?'today':''}" title="${record?record.session:''}"><b>${day}</b>${record?`<i class="record ${record.session==='力量 A'?'strength-a':record.session==='力量 B'?'strength-b':record.session==='跑走耐力'?'run':'recovery'}">${typeLabel(record.session)}</i>`:''}</span>`);}$('#calendar-grid').innerHTML=cells.join('');const total=state.completedSessions.filter(item=>item.date.startsWith(`${year}-${String(month+1).padStart(2,'0')}`)).length,rests=state.restDays.filter(key=>key.startsWith(`${year}-${String(month+1).padStart(2,'0')}`)).length;$('#calendar-summary').textContent=total||rests?`本月已完成 ${total} 次训练，安排 ${rests} 天休息`:'本月从第一份训练开始。';}
function render(){const current=sessions[state.session];$('#session-title').textContent=state.session;$('#session-summary').textContent=current.summary;$('#workout-list').innerHTML=current.exercises.map(([name,dose,videoId])=>`<article class="exercise"><span><strong>${name}</strong><small>${dose}</small>${setButtons(name,dose)}</span><button class="video-link" data-video-id="${videoId}" data-video-title="${name}" data-motion="${motionType(name)}" aria-label="查看 ${name} 图文指导" title="图文指导">▷</button></article>`).join('');$('#repair-list').innerHTML=repairs.map(([name,dose,videoId])=>`<article class="repair"><strong>${name}</strong><small>${dose}</small>${setButtons(name,dose)}<button class="repair-video" data-video-id="${videoId}" data-video-title="${name}" data-motion="${motionType(name)}">图文指导 ▷</button></article>`).join('');const done=state.completedSessions.some(item=>item.date===today),resting=state.restDays.includes(today);$('#complete-session').textContent=done?'今日已完成':resting?'今日休息':'完成今日训练';$('#complete-session').classList.toggle('completed',done||resting);$('#complete-session').disabled=resting;$('#rest-today').textContent=resting?'恢复今日训练':'今日休息';$('#rest-today').disabled=done;document.querySelectorAll('[data-readiness]').forEach(button=>button.classList.toggle('selected',button.dataset.readiness===state.readiness));renderCalendar();}
function wikiTerm(name){return {'高位俯卧撑':'俯卧撑','扶椅后撤箭步蹲':'箭步蹲','单腿臀桥':'臀桥','俯卧 Y-T 抬臂':'肩胛骨','墙面肩胛俯卧撑':'肩胛骨','慢速提踵':'提踵','踝关节活动':'踝关节','热身快走':'快走','放松慢走':'快走','轻松快走':'快走','跑走交替':'跑步'}[name]||name;}
function openVideo(button){const name=button.dataset.videoTitle,guide=guides[name]||{steps:['先用舒适范围开始，动作保持缓慢可控。','训练中持续呼吸，避免借力或追求极限幅度。','出现疼痛、不稳或麻木时停止并改为恢复训练。']},images=guide.images||[];$('#video-title').textContent=`${name}指导`;$('#guide-images').innerHTML=images.map((src,index)=>`<img class="guide-image" src="${src}" alt="${name}动作示意 ${index+1}" loading="eager">`).join('');$('#guide-empty').textContent=images.length?'':'暂无已核验的公开授权图片，请按下方三步要点完成。';$('#guide-steps').innerHTML=guide.steps.map(step=>`<li>${step}</li>`).join('');$('#wiki-link').href=`https://baike.baidu.com/item/${encodeURIComponent(wikiTerm(name))}`;$('#video-credit').textContent=images.length?'图片：项目作者使用 AI 图像生成工具制作。':'';$('#video-dialog').showModal();}
let activeFeedbackProfile;
function openFeedback(button){const name=button.dataset.feedbackExercise;activeFeedbackProfile=feedbackProfile(name);$('#feedback-dialog').dataset.exercise=name;$('#feedback-title').textContent=`${name}状态反馈`;$('#feedback-context').textContent=activeFeedbackProfile.context;$('#feedback-options').innerHTML=activeFeedbackProfile.options.map((option,index)=>`<button data-feedback-kind="${index}"><strong>${option[0]}</strong><span>${option[1]}</span></button>`).join('');$('#feedback-result').hidden=true;$('#feedback-options').hidden=false;$('#feedback-dialog').showModal();}
function showFeedbackResult(kind){const index=Number(kind),name=$('#feedback-dialog').dataset.exercise,shouldCap=index===0||(/深蹲|箭步|静蹲/.test(name)&&index===2);if(shouldCap){state.cappedExercises[setKey(name)]=activeFeedbackProfile.options[index][0];save();render();}$('#feedback-result').textContent=`${activeFeedbackProfile.options[index][2]}${shouldCap?' 已将本动作标为“已达上限”。':''}`;$('#feedback-options').hidden=true;$('#feedback-result').hidden=false;}
$('#readiness-options').addEventListener('click',event=>{if(!event.target.dataset.readiness)return;state.readiness=event.target.dataset.readiness;const messages={low:'今天降低训练量：改恢复日或每个动作少做一组。',normal:'按计划完成，所有动作保留 2 次余力。',high:'状态很好也不练到力竭。任选一个动作每组加 1 次。'};$('#status-copy').textContent=messages[state.readiness];save();render();});
$('#switch-session').onclick=()=>{const keys=Object.keys(sessions),index=keys.indexOf(state.session);state.session=keys[(index+1)%keys.length];save();render();};
let completionToastTimer;
function celebrateCompletion(){const button=$('#complete-session'),toast=$('#completion-toast');button.classList.add('celebrate');navigator.vibrate?.([20,45,35]);toast.classList.add('show');clearTimeout(completionToastTimer);completionToastTimer=setTimeout(()=>toast.classList.remove('show'),2200);}
$('#complete-session').onclick=()=>{if(state.completedSessions.some(item=>item.date===today)||state.restDays.includes(today))return;state.completedSessions.push({date:today,session:state.session});save();render();celebrateCompletion();};
$('#rest-today').onclick=()=>{if(state.restDays.includes(today)){state.restDays=state.restDays.filter(day=>day!==today);}else if(!state.completedSessions.some(item=>item.date===today)){state.restDays.push(today);}save();render();};
document.addEventListener('click',event=>{const button=event.target.closest('[data-video-id]');if(!button)return;event.preventDefault();event.stopPropagation();openVideo(button);});
document.addEventListener('click',event=>{const button=event.target.closest('[data-feedback-exercise]');if(!button)return;openFeedback(button);});
document.addEventListener('click',event=>{const button=event.target.closest('[data-rest-exercise]');if(!button)return;const name=button.dataset.restExercise;$('#rest-title').textContent=`${name}休息`;$('#rest-options').innerHTML=restParts(name).map(part=>`<button data-rest-part="${part}"><strong>${part}未恢复</strong><span>今天暂停本动作的剩余组数</span></button>`).join('');$('#rest-dialog').dataset.exercise=name;$('#rest-dialog').showModal();});
document.addEventListener('click',event=>{const button=event.target.closest('[data-set-name]');if(!button)return;const name=button.dataset.setName,index=Number(button.dataset.setIndex),key=setKey(name),current=checkedSets(name),willComplete=!current.includes(index);state.setChecks[key]=willComplete?[...current,index].sort((a,b)=>a-b):current.filter(item=>item!==index);save();render();if(willComplete){button.classList.add('pop');navigator.vibrate?.(25);}});
document.addEventListener('click',event=>{const button=event.target.closest('[data-resume-exercise]');if(!button)return;delete state.restedExercises[setKey(button.dataset.resumeExercise)];save();render();});
document.addEventListener('click',event=>{const button=event.target.closest('[data-resume-cap]');if(!button)return;delete state.cappedExercises[setKey(button.dataset.resumeCap)];save();render();});
$('#close-video').onclick=()=>{$('#guide-images').innerHTML='';$('#video-dialog').close();};
$('#feedback-options').addEventListener('click',event=>{const button=event.target.closest('[data-feedback-kind]');if(button)showFeedbackResult(button.dataset.feedbackKind);});
$('#rest-options').addEventListener('click',event=>{const button=event.target.closest('[data-rest-part]');if(!button)return;state.restedExercises[setKey($('#rest-dialog').dataset.exercise)]=button.dataset.restPart;save();$('#rest-dialog').close();render();});
$('#previous-month').onclick=()=>{calendarCursor=new Date(calendarCursor.getFullYear(),calendarCursor.getMonth()-1,1);renderCalendar();};
$('#next-month').onclick=()=>{calendarCursor=new Date(calendarCursor.getFullYear(),calendarCursor.getMonth()+1,1);renderCalendar();};
$('#settings-button').onclick=()=>$('#settings-dialog').showModal();$('#save-settings').onclick=()=>{state.reminder=$('#reminder-time').value;save();if('Notification'in window&&Notification.permission==='default')Notification.requestPermission();};
$('#today-date').textContent=new Intl.DateTimeFormat('zh-CN',{month:'long',day:'numeric',weekday:'short'}).format(new Date());prepareToday();render();checkReminder();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');
