const languageKey='train-well-language-v2';
const language=localStorage.getItem(languageKey)==='zh'?'zh':'en';
const en={
  '练得刚好':'Train Well','训练安排':'Training plan','选择今天的份额':"Choose today's session",'每日状态':'Daily readiness','今天身体感觉如何？':'How does your body feel today?','累':'Low','正常':'Normal','状态好':'Great','按计划完成，所有动作保留 2 次余力。':'Follow the plan and keep two reps in reserve.','按身体状态选择一份可完成的训练。计划始终可以调整。':'Choose a session that fits how you feel today. You can always adjust it.','恢复活动':'Recovery','每日 5 分钟修复':'Daily recovery','选择一处稳定支撑，按舒适节奏完成四个动作。需要时可查看图文要点。':'Use a stable support and complete four movements at a comfortable pace. Open a guide whenever you need it.','今日训练':"Today's training",'今日份额':"Today's session",'切换':'Switch','训练记录':'Training record','本月进度':'This month','本月':'This month','偏好设置':'Preferences','训练设置':'Training settings','每日提醒时间':'Daily reminder time','保存设置':'Save settings','计划':'Plan','修复':'Recovery','记录':'Records','设置':'Settings','完成今日训练':"Complete today's workout",'今日已完成':'Completed today','今日休息':'Rest day','恢复今日训练':"Resume today's workout",'本月从第一份训练开始。':'Start this month with your first session.','网页只能在打开时提醒。安装到主屏幕后，可以开启浏览器通知；稳定的定时推送需要部署推送服务。':'The website can remind you only while it is open. When installed, you can enable browser notifications; reliable scheduled notifications require a push service.','今日训练已记录':"Today's workout recorded",'动作指导':'Movement guide','正在加载动作指导。':'Loading movement guide.','在百度百科查阅':'Read on Wikipedia','动作状态反馈':'Movement check-in','动作休息':'Rest this movement','选择今天尚未恢复的部位。':'Choose the area that has not recovered today.','关闭':'Close','打开设置':'Open settings','上个月':'Previous month','下个月':'Next month','一':'Mon','二':'Tue','三':'Wed','四':'Thu','五':'Fri','六':'Sat','日':'Sun',
  '力量 A':'Strength A','力量 B':'Strength B','跑走耐力':'Run-walk endurance','恢复日':'Recovery day','自重深蹲':'Bodyweight squat','高位俯卧撑':'Incline push-up','臀桥':'Glute bridge','扶椅后撤箭步蹲':'Supported reverse lunge','死虫式':'Dead bug','侧桥':'Side plank','靠墙静蹲':'Wall sit','单腿臀桥':'Single-leg glute bridge','墙面滑手':'Wall slide','俯卧 Y-T 抬臂':'Prone Y-T raise','平板支撑':'Forearm plank','热身快走':'Warm-up brisk walk','跑走交替':'Run-walk intervals','放松慢走':'Cool-down walk','小腿拉伸':'Calf stretch','轻松快走':'Easy brisk walk','踝关节活动':'Ankle mobility','墙面肩胛俯卧撑':'Wall scapular push-up','呼吸放松':'Relaxed breathing','单脚站立':'Single-leg stand','慢速提踵':'Slow calf raise','俯卧撑':'Push-up','箭步蹲':'Lunge (exercise)','肩胛骨':'Scapula','提踵':'Calf raise','踝关节':'Ankle','快走':'Walking','跑步':'Running',
  '下肢、推与核心。约 35-45 分钟，动作稳定优先。':'Lower body, pushing, and core. About 35-45 minutes. Prioritize steady movement.','臀腿、肩胛稳定与核心。约 30-40 分钟，动作稳定优先。':'Glutes, legs, scapular stability, and core. About 30-40 minutes. Prioritize steady movement.','保持能说完整句子的强度；不适时改为快走。':'Keep an intensity where you can speak in full sentences. Switch to walking if uncomfortable.','今天的份额是恢复。轻松完成即可，不追求训练感。':'Today is for recovery. Keep it easy; no need to chase intensity.',
  '休息':'Rest','状态反馈':'Check in','图文指导':'Movement guide','恢复动作':'Resume movement','恢复进度':'Resume progress','已达上限':"Today's limit",'本动作休息':'Movement resting','今天不再增加':'Do not add more today','本动作已完成':'Movement complete','本动作完成':'Movement complete','取消计时':'Cancel timer','已选择':'Selected','选择':'Choose','设置已保存':'Settings saved','✓ 今日训练已记录':"✓ Today's workout recorded",'暂无已核验的公开授权图片，请按下方三步要点完成。':'No verified public-use image is available. Follow the three steps below.','图片：项目作者使用 AI 图像生成工具制作。':'Images were created by the project author with an AI image-generation tool.','今天降低训练量：改恢复日或每个动作少做一组。':'Reduce today\'s workload: choose Recovery day or do one fewer set per movement.','状态很好也不练到力竭。任选一个动作每组加 1 次。':'Even on a great day, do not train to failure. Add one rep per set to one movement if you choose.'
};
function t(value){if(language!=='en'||!value)return value;const leading=value.match(/^\s*/)[0],trailing=value.match(/\s*$/)[0],core=value.trim();let output=en[core]||core;output=output.replace(/^已完成 (\d+) \/ (\d+) 组$/,'$1 / $2 sets complete').replace(/第\s*(\d+)\s*组/g,'Set $1').replace(/左\s*(\d+)\s*组/g,'Left set $1').replace(/右\s*(\d+)\s*组/g,'Right set $1').replace(/(\d+(?:-\d+)?)\s*组/g,'$1 sets').replace(/每侧/g,'each side').replace(/(\d+(?:-\d+)?)\s*次/g,'$1 reps').replace(/(\d+(?:-\d+)?)\s*分钟/g,'$1 min').replace(/(\d+(?:-\d+)?)\s*秒/g,'$1 sec').replace(/(\d+(?:-\d+)?)\s*轮/g,'$1 rounds').replace(/(\d+) 个动作/g,'$1 movements').replace(/^本月已完成 (\d+) 次训练，安排 (\d+) 天休息$/,'$1 workouts completed and $2 rest days this month.').replace(/^下一组：/,'Next: ').replace(/^完成\s*/,'Complete ').replace(/^撤销\s*/,'Undo ').replace(/^开始\s*/,'Start ').replace(/^计时\s*/,'Timer ');return `${leading}${output}${trailing}`;}
function englishMarkup(markup){if(language!=='en')return markup;const template=document.createElement('template');template.innerHTML=markup;const walker=document.createTreeWalker(template.content,NodeFilter.SHOW_TEXT);const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);nodes.forEach(node=>node.nodeValue=t(node.nodeValue));template.content.querySelectorAll('[aria-label],[title]').forEach(element=>['aria-label','title'].forEach(attribute=>{if(element.hasAttribute(attribute))element.setAttribute(attribute,t(element.getAttribute(attribute)));}));return template.innerHTML;}
function localizePage(){if(language!=='en')return;document.documentElement.lang='en';document.title='Train Well';const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT,{acceptNode(node){return node.parentElement?.closest('script,style')?NodeFilter.FILTER_REJECT:NodeFilter.FILTER_ACCEPT;}});const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);nodes.forEach(node=>node.nodeValue=t(node.nodeValue));document.querySelectorAll('[aria-label],[title]').forEach(element=>['aria-label','title'].forEach(attribute=>{if(element.hasAttribute(attribute))element.setAttribute(attribute,t(element.getAttribute(attribute)));}));$('#language-toggle').textContent='中文';$('#language-toggle').setAttribute('aria-label','Switch to Chinese');}
const sessions = {
  '力量 A': { summary:'下肢、推与核心。约 35-45 分钟，动作稳定优先。', exercises:[['自重深蹲','3 组 × 10-15 次','YaXPRqUwItQ'],['高位俯卧撑','3 组 × 8-12 次','0GsVJsS6474'],['臀桥','3 组 × 12-20 次','wPM8icPu6H8'],['扶椅后撤箭步蹲','2-3 组 × 每侧 8-10 次','xrPteyQLGAo'],['死虫式','3 组 × 每侧 6-10 次','I5xbsA71v1A'],['侧桥','2 组 × 每侧 15-30 秒','K2VljzCC16g']] },
  '力量 B': { summary:'臀腿、肩胛稳定与核心。约 30-40 分钟，动作稳定优先。', exercises:[['靠墙静蹲','3 组 × 35-60 秒','y-wV4Venusw'],['单腿臀桥','3 组 × 每侧 8-12 次','wPM8icPu6H8'],['高位俯卧撑','3 组 × 8-12 次','0GsVJsS6474'],['墙面滑手','3 组 × 8-12 次','CiM-s8I5dl8'],['俯卧 Y-T 抬臂','各 2 组 × 6-10 次','CiM-s8I5dl8'],['平板支撑','3 组 × 20-40 秒','pSHjTRCQxIw']] },
  '跑走耐力': { summary:'保持能说完整句子的强度；不适时改为快走。', exercises:[['热身快走','8 分钟','ml6cT4AZdqI'],['跑走交替','跑 2 分钟 + 走 2 分钟，7-8 轮','9L2b2khySLE'],['放松慢走','5 分钟','ml6cT4AZdqI'],['小腿拉伸','每侧 2 组 × 30 秒','YQmpO9VT2X4']] },
  '恢复日': { summary:'今天的份额是恢复。轻松完成即可，不追求训练感。', exercises:[['轻松快走','20-30 分钟','ml6cT4AZdqI'],['踝关节活动','每侧 1 分钟','IikP_teeLkI'],['墙面肩胛俯卧撑','2 组 × 10-15 次','g9d3B9J1Y9U'],['呼吸放松','3 分钟','aNXKjGFUlMs']] }
};
const repairs=[['单脚站立','每侧 2 组 × 30 秒','IikP_teeLkI'],['慢速提踵','3 组 × 12-20 次','YQmpO9VT2X4'],['墙面肩胛俯卧撑','2 组 × 10-15 次','g9d3B9J1Y9U'],['墙面滑手','2 组 × 8-12 次','CiM-s8I5dl8']];
const guides={
  '自重深蹲':{images:['assets/guides/bodyweight-squat-ai.png'],steps:['双脚与髋同宽，脚尖自然微外，胸口保持打开。','臀部先向后坐，膝盖沿脚尖方向移动；下到可稳定控制的深度。','脚掌均匀发力站起，不要用膝盖内扣或借反弹起身。']},
  '高位俯卧撑':{images:['assets/guides/incline-pushup-ai.png'],steps:['双手放在稳定的高支撑面，身体从头到脚跟成一条直线。','吸气下降，肘部向后约 30-45 度，不耸肩。','呼气推回；出现不稳、锐痛或麻木时立即停止。']},
  '臀桥':{images:['assets/guides/bridge-start.svg','assets/guides/bridge-up.svg'],steps:['仰卧屈膝，脚跟在膝盖正下方附近，腰背自然贴地。','用脚跟轻推地面，收紧臀部将髋抬到躯干与大腿接近直线。','顶部停一秒后慢慢下放；不要靠过度挺腰抬高。']},
  '扶椅后撤箭步蹲':{images:['assets/guides/lunge-start.svg','assets/guides/lunge-down.svg'],steps:['轻扶稳固椅背，先站稳，后脚向后迈一小步。','垂直下沉，前膝对准第二脚趾方向，重心保持在两脚之间。','以前脚推地回到站姿；脚踝不稳就缩短步幅或改靠墙静蹲。']},
  '死虫式':{images:['assets/guides/dead-bug-ai.png'],steps:['仰卧，髋膝 90 度，双臂伸向天花板，轻轻收紧腹部。','缓慢伸远一侧腿和对侧手臂：图中是左臂向后、右腿向前。','呼气回到起始位，再换边；范围小也没关系。']},
  '侧桥':{images:['assets/guides/side-plank.png'],steps:['前臂放在肩正下方，双腿伸直或屈膝降低难度。','抬起髋部，让头、肩、髋、踝尽量连成直线。','保持呼吸，髋下沉或肩不适时结束该组。']},
  '靠墙静蹲':{images:['assets/guides/wall-sit-ai.png'],steps:['背部贴墙，双脚向前迈出约半步到一步。','慢慢下滑到无膝痛且能稳定的角度，膝盖对准脚尖。','全脚掌着地、持续呼吸；膝痛或脚踝不适就提高角度。']},
  '单腿臀桥':{images:['assets/guides/single-leg-bridge-ai.png'],steps:['先完成双腿臀桥姿势，再将一侧脚轻轻抬离地面。','支撑脚跟推地抬髋，骨盆尽量保持水平。','动作变形时改回双腿臀桥，不用追求抬得很高。']},
  '墙面滑手':{images:['assets/guides/wall-slide-ai.png'],steps:['背靠墙或面向墙站立，肋骨轻轻收住，肩颈放松。','双手沿墙缓慢上滑，只到肩部稳定、无痛的范围。','下滑时保持肩胛平稳；卡住、不稳或疼痛就停止。']},
  '俯卧 Y-T 抬臂':{images:['assets/guides/prone-yt-ai.png'],steps:['俯卧，额头轻贴毛巾，先把肩膀远离耳朵。','分别以 Y 和 T 形缓慢抬臂，幅度小、停一秒即可。','不要甩手或耸肩；出现不稳感时跳过。']},
  '平板支撑':{images:['assets/guides/forearm-plank-ai.png'],steps:['前臂在肩正下方，双腿向后伸直，脚尖支地。','收紧臀腹，让身体保持长直线，不塌腰也不抬臀。','正常呼吸；姿势变形前结束，比硬撑更有效。']},
  '热身快走':{images:['assets/guides/brisk-walk-ai.png'],steps:['前 2 分钟用舒适步速，脚掌轻柔落地。','逐步加快到身体微热但仍能完整说话的速度。','若脚踝疼痛或不稳，改为更慢速度并缩短时间。']},
  '跑走交替':{images:['assets/guides/run-walk-ai.png'],steps:['先走 8 分钟热身，再用轻松跑开始每组。','跑段保持能控制的步频，不冲刺；走段让呼吸恢复。','脚踝出现疼痛、肿胀或不稳时当次改为全程快走。']},
  '放松慢走':{images:['assets/guides/brisk-walk-ai.png'],steps:['训练后立刻切换为轻松步速。','让呼吸逐渐平稳，双肩放松。','至少走 5 分钟，再进行轻柔拉伸。']},
  '小腿拉伸':{images:['assets/guides/calf-stretch-ai.png'],steps:['双手扶墙，一脚在后，后脚跟踩实地面。','后膝伸直时拉腓肠肌；微屈后膝时拉比目鱼肌。','保持轻微牵拉感，不弹震，也不要忍痛。']},
  '轻松快走':{images:['assets/guides/brisk-walk-ai.png'],steps:['选择平坦路线，步速以能轻松交谈为准。','脚步落地保持平稳，避免急转和坡度冲刺。','脚踝不适就提前结束，不把恢复日练成高强度日。']},
  '踝关节活动':{images:['assets/guides/ankle-circle.svg'],steps:['坐姿或扶墙站立，缓慢画圈活动脚踝。','分别做脚尖上勾、下压和内外转，幅度以舒适为准。','扭伤旧处若出现刺痛或肿胀，不要继续活动。']},
  '墙面肩胛俯卧撑':{images:['assets/guides/wall-scapular-push-ai.png'],steps:['双手撑墙，手臂伸直，身体保持稳定。','不屈肘，只让肩胛轻轻靠近再推远。','动作小且慢，出现任何不稳感都应停止。']},
  '呼吸放松':{images:['assets/guides/diaphragmatic-breathing-ai.png'],steps:['舒适躺下或坐直，一手放在腹部。','缓慢吸气让腹部轻轻鼓起，呼气比吸气稍长。','连续做 3 分钟，不憋气也不刻意用力。']},
  '单脚站立':{images:['assets/guides/single-leg-stand-ai.png'],steps:['站在墙边或椅旁，先双脚稳定后抬起一只脚。','支撑脚三点均匀着地，视线看前方。','脚踝摇晃明显时可轻触墙面，不必强行闭眼。']},
  '慢速提踵':{images:['assets/guides/slow-calf-raise-ai.png'],steps:['扶墙站稳，双脚平行，重心均匀落在前脚掌与脚跟。','缓慢抬起脚跟至最高点，停一秒。','用 2-3 秒慢慢放下；脚踝痛就减小幅度。']}
};
const $=selector=>document.querySelector(selector);
function localDateKey(date=new Date()){const y=date.getFullYear(),m=String(date.getMonth()+1).padStart(2,'0'),d=String(date.getDate()).padStart(2,'0');return `${y}-${m}-${d}`;}
const today=localDateKey();
let state={};
try{state=JSON.parse(localStorage.getItem('train-well-state')||'{}')||{};}catch{state={};}
if(typeof state!=='object'||Array.isArray(state))state={};
state.completedSessions=Array.isArray(state.completedSessions)?state.completedSessions:[];
state.setChecks=state.setChecks||{};
state.restedExercises=state.restedExercises||{};
state.cappedExercises=state.cappedExercises||{};
state.restDays=Array.isArray(state.restDays)?state.restDays:[];
state.readiness=state.readiness||'normal';
state.activeTimers=state.activeTimers||{};
let calendarCursor=new Date(new Date().getFullYear(),new Date().getMonth(),1);
function save(){try{localStorage.setItem('train-well-state',JSON.stringify(state));}catch{} }
function latestStrength(){return [...state.completedSessions].reverse().find(item=>item.session==='力量 A'||item.session==='力量 B');}
function recommendedSession(){const last=latestStrength();return last?.session==='力量 A'?'力量 B':last?.session==='力量 B'?'力量 A':'力量 A';}
function prepareToday(){if(state.planDate===today&&sessions[state.session])return;state.session=recommendedSession();state.planDate=today;save();}
function typeLabel(session){return session==='力量 A'?'A':session==='力量 B'?'B':session==='跑走耐力'?'跑':'修';}
function motionType(name){if(/深蹲|箭步|静蹲/.test(name))return 'squat';if(/俯卧撑|滑手|Y-T/.test(name))return 'push';if(/臀桥/.test(name))return 'bridge';if(/跑|走|踵|踝|站立/.test(name))return 'walk';return 'core';}
function setCount(dose){const match=dose.match(/(\d+)(?:-\d+)?\s*组/);return match?Number(match[1]):1;}
function setSequence(name,dose){const count=setCount(dose);return /每侧/.test(dose)?Array.from({length:count},(_,index)=>[`左 ${index+1} 组`,`右 ${index+1} 组`]).flat():Array.from({length:count},(_,index)=>`第 ${index+1} 组`);}
function timerSeconds(dose){const match=dose.match(/(\d+)(?:-\d+)?\s*秒/);return match?Number(match[1]):0;}
function setKey(name,scope='plan'){return scope==='repair'?`${today}|repair|${name}`:`${today}|${state.session}|${name}`;}
function timerKey(name,index,scope='plan'){return `${setKey(name,scope)}|${index}`;}
function checkedSets(name,scope='plan'){return state.setChecks[setKey(name,scope)]||[];}
function planExercisesComplete(){return sessions[state.session].exercises.every(([name,dose])=>{const key=setKey(name),sequence=setSequence(name,dose);return !state.restedExercises[key]&&!state.cappedExercises[key]&&sequence.every((_,index)=>checkedSets(name).includes(index));});}
function completeTodayIfReady(){if(state.completedSessions.some(item=>item.date===today)||state.restDays.includes(today)||!planExercisesComplete())return false;state.completedSessions.push({date:today,session:state.session});save();celebrateCompletion();return true;}
function restParts(name){if(/深蹲|箭步|静蹲/.test(name))return ['大腿或臀部','膝盖','脚踝'];if(/俯卧撑/.test(name))return ['胸臂','肩膀','手腕'];if(/臀桥/.test(name))return ['臀部','后侧大腿','腰部'];if(/死虫|侧桥|平板/.test(name))return ['腹部','腰部','肩部'];if(/滑手|Y-T|肩胛/.test(name))return ['肩胛','肩膀','颈部'];if(/提踵|小腿|踝|单脚/.test(name))return ['小腿','脚踝','足部'];if(/跑|走/.test(name))return ['呼吸恢复','膝盖','脚踝或足部'];if(/呼吸/.test(name))return ['呼吸节奏','胸口不适','头晕'];return ['目标肌肉','关节','整体疲劳'];}
function restButton(name){return englishMarkup(`<button class="set-rest" data-rest-exercise="${name}">休息</button>`);}
function baseFeedbackProfile(name){if(/深蹲|箭步|静蹲/.test(name))return {context:'关注腿部用力、膝盖与脚踝的感受。',options:[['腿部发紧','大腿或臀部紧绷，但没有关节痛','休息 60-90 秒。下一组减少 2-4 次或缩短下蹲幅度；后撤箭步蹲仍紧时改为 2 组即可。'],['膝踝不适','膝盖、脚踝刺痛或站不稳','停止该动作，改为无痛范围的轻松走动或结束下肢训练；症状持续、肿胀或影响走路时咨询专业人士。']]};if(/俯卧撑/.test(name))return {context:'关注胸臂疲劳，以及肩膀和手腕的承受感。',options:[['胸臂疲劳','胸、三头肌发热或发紧','休息 60-90 秒；下一组降低次数或提高支撑面，不必补足原计划。'],['肩腕不适','肩前侧或手腕疼痛、卡住','停止该动作；可改为墙面肩胛俯卧撑。疼痛持续或影响日常活动时咨询专业人士。']]};if(/臀桥/.test(name))return {context:'臀部发力应更明显，腰部不应成为主要压力点。',options:[['臀腿疲劳','臀部或后侧大腿发紧','休息 60 秒，下一组减少次数或改回双腿臀桥，保持动作范围可控。'],['腰部不适','腰部顶住、疼痛或代偿明显','停止该动作，降低抬髋高度；当次不要继续加量，持续不适时咨询专业人士。']]};if(/死虫|侧桥|平板/.test(name))return {context:'核心动作以稳定躯干为先，不靠憋气或硬撑。',options:[['腹部疲劳','腹部发紧、发热但姿势仍稳定','休息 45-60 秒，下一组缩短时间或减小手脚伸展范围。'],['腰肩不适','腰部拱起、肩部顶住或疼痛','停止该动作；死虫式缩小范围，桥式动作可改屈膝版本。持续不适时咨询专业人士。']]};if(/滑手|Y-T|肩胛/.test(name))return {context:'肩胛控制应平稳，颈部不应代偿用力。',options:[['肩胛疲劳','肩胛周围发酸、轻微疲劳','休息 45-60 秒，下一组减小抬举幅度或次数。'],['肩颈不适','肩部卡住、刺痛或颈部紧张明显','停止该动作，放松后仅在无痛范围活动；症状持续时咨询专业人士。']]};if(/提踵|小腿|踝|单脚/.test(name))return {context:'关注小腿疲劳与脚踝稳定，不追求极限幅度。',options:[['小腿疲劳','小腿酸胀或紧绷','休息 45-60 秒，下一组减少次数或幅度，慢慢下放。'],['脚踝不适','疼痛、肿胀或明显摇晃','停止该动作，避免继续单脚负重；症状持续或加重时咨询专业人士。']]};if(/跑|走/.test(name))return {context:'跑走训练先看呼吸、步态和下肢是否稳定。',options:[['呼吸偏急','无法完整说一句话','降低为快走，直到呼吸恢复；下一轮缩短跑段或减少轮数。'],['下肢不适','膝、踝、足部疼痛或步态不稳','当次改为轻松走或结束训练；肿胀、持续疼痛或影响走路时咨询专业人士。']]};if(/呼吸/.test(name))return {context:'呼吸放松应舒适、自然，不应憋气或头晕。',options:[['难以放松','呼气不顺或身体紧绷','缩短到 1 分钟，恢复自然呼吸，不必刻意深吸。'],['头晕不适','头晕、胸闷或不舒服','停止练习，坐下或侧卧休息；症状持续或严重时寻求专业帮助。']]};return {context:'根据动作控制感与身体反应决定下一步。',options:[['局部疲劳','目标肌肉发紧但没有疼痛','休息 45-60 秒，下一组减少次数或幅度。'],['疼痛或不稳','刺痛、麻木、无力或失去控制','停止该动作；症状持续或影响日常活动时咨询专业人士。']]};}
function feedbackProfile(name){const profile=baseFeedbackProfile(name);const followUp=/深蹲|箭步|静蹲/.test(name)?['左右差异','单侧明显更累或站姿偏向一边','下一组从较弱侧开始，左右两边都按较弱侧次数完成；仍差异明显就结束该动作。']:/俯卧撑/.test(name)?['手臂先力竭','手臂先撑不住，胸部发力感不足','下一组提高支撑面并减少次数，身体保持直线；不必硬撑完成原次数。']:/臀桥/.test(name)?['后侧大腿抢力','大腿后侧比臀部更先紧绷','把脚跟略靠近臀部，降低抬髋高度；下一组减少次数。']:/死虫|侧桥|平板/.test(name)?['呼吸憋住','为了保持姿势而不自觉憋气','结束当前组，恢复自然呼吸；下一组缩短时间或减小范围。']:/滑手|Y-T|肩胛/.test(name)?['颈部代偿','脖子或斜方肌比肩胛更紧','降低手臂高度，先放松肩膀；下一组只做无颈部紧张的范围。']:/提踵|小腿|踝|单脚/.test(name)?['抽筋趋势','小腿开始跳动或接近抽筋','停止该组，轻柔活动脚踝并补水；当天不要继续增加提踵或跑量。']:/跑|走/.test(name)?['步伐变重','落地变重、步态开始散乱','当次改为轻松走，缩短下一跑段或提前结束训练。']:/呼吸/.test(name)?['呼吸过深','越做越紧或出现轻微头晕','恢复平常呼吸，不要强行深吸；不适持续则停止练习。']:['呼吸乱了','动作时难以保持自然呼吸','休息 45-60 秒，下一组减小次数或幅度，先恢复可控呼吸。'];profile.options.push(followUp);return profile;}
function feedbackButton(name,completed){return englishMarkup(`<button class="set-feedback" data-feedback-exercise="${name}" data-feedback-sets="${completed}" aria-label="${name}状态反馈">状态反馈</button>`);}
function formatSeconds(seconds){const safe=Math.max(0,Math.ceil(seconds));return `${String(Math.floor(safe/60)).padStart(2,'0')}:${String(safe%60).padStart(2,'0')}`;}
function completeSet(name,index,scope='plan'){const key=setKey(name,scope),current=checkedSets(name,scope);if(current.includes(index))return;state.setChecks[key]=[...current,index].sort((a,b)=>a-b);state.lastProgressChange={key,name,index,scope};save();}
function finishElapsedTimers(){let changed=false;Object.entries(state.activeTimers).forEach(([key,timer])=>{if(Date.now()<timer.endsAt)return;completeSet(timer.name,timer.index,timer.scope||'plan');delete state.activeTimers[key];changed=true;});if(changed){save();render();}}
function setButtons(name,dose,compact=false,scope='plan'){const checked=checkedSets(name,scope),sequence=setSequence(name,dose),count=sequence.length,key=setKey(name,scope),rested=state.restedExercises[key],capped=state.cappedExercises[key],allDone=checked.length===count,next=sequence.findIndex((_,index)=>!checked.includes(index)),seconds=timerSeconds(dose),timer=next>=0?state.activeTimers[timerKey(name,next,scope)]:null,scopeAttribute=`data-progress-scope="${scope}"`,status=rested?`${rested}未恢复，今日休息`:capped?'已达上限，今天不再增加':allDone?'本动作已完成':`下一组：${sequence[next]}`,summary=rested?'本动作休息':capped?'已达上限':`${checked.length} / ${count} 组`;let action='';if(rested)action=`<button class="set-undo" data-resume-exercise="${name}" ${scopeAttribute}>恢复动作</button>`;else if(capped)action=`<button class="set-undo" data-resume-cap="${name}" ${scopeAttribute}>恢复进度</button>`;else if(allDone)action='<button class="set-complete" disabled>✓ 本动作完成</button>';else if(timer)action=`<button class="set-timer" disabled>计时 ${formatSeconds((timer.endsAt-Date.now())/1000)}</button><button class="set-undo" data-cancel-timer="${name}" data-set-index="${next}" ${scopeAttribute}>取消计时</button>`;else if(seconds)action=`<button class="set-next" data-start-timer="${name}" data-set-index="${next}" data-timer-seconds="${seconds}" ${scopeAttribute}>开始 ${sequence[next]} · ${seconds} 秒</button>`;else action=`<button class="set-next" data-complete-set="${name}" data-set-index="${next}" ${scopeAttribute}>完成 ${sequence[next]}</button>`;return englishMarkup(`<div class="set-summary"><strong class="${capped?'at-limit':''}">${summary}</strong><span class="${allDone?'all-done':''}">${status}</span></div><div class="set-bar ${capped?'at-limit':''}" aria-label="已完成 ${checked.length} / ${count} 组"><i style="width:${checked.length/count*100}%"></i></div><div class="set-checks">${action}${compact?'':`${feedbackButton(name,checked.length)}${rested||capped?'':restButton(name)}`}${checked.map(index=>`<button class="set-undo" data-undo-set="${name}" data-set-index="${index}" ${scopeAttribute}>撤销 ${sequence[index]}</button>`).join('')}</div>`);}
function checkReminder(){if(!state.reminder||!('Notification'in window)||Notification.permission!=='granted')return;const [hour,minute]=state.reminder.split(':').map(Number),now=new Date(),due=new Date();due.setHours(hour,minute,0,0);const key=`train-well-reminded-${today}`;if(now>=due&&!localStorage.getItem(key)){new Notification('今天的训练份额',{body:`${state.session}：${sessions[state.session].summary}`,icon:'app-icon-180.png'});localStorage.setItem(key,'1');}}
const dailyQuotes=[['盛年不重来，一日难再晨。及时当勉励，岁月不待人。','Prime years do not come again; a day does not dawn twice. Take heart in time, for the years do not wait.','陶渊明《杂诗·其一》 / Tao Yuanming, “Miscellaneous Poems I”'],['其实地上本没有路，走的人多了，也便成了路。','The earth had no roads to begin with; when many people walk the same way, a road comes into being.','鲁迅《故乡》 / Lu Xun, “My Old Home”'],['且将新火试新茶，诗酒趁年华。','Light a fresh fire, brew new tea; enjoy poetry and wine while still in your prime.','苏轼《望江南·超然台作》 / Su Shi, “Looking South of the Yangtze”'],['To strive, to seek, to find, and not to yield.','奋斗，探索，发现，永不屈服。','Alfred, Lord Tennyson, “Ulysses”'],['It is only with the heart that one can see rightly; what is essential is invisible to the eye.','只有用心才能看得清楚；本质的东西，眼睛是看不见的。','Antoine de Saint-Exupéry, The Little Prince'],['A man can be destroyed but not defeated.','人可以被毁灭，但不能被打败。','Ernest Hemingway, The Old Man and the Sea'],['All we have to decide is what to do with the time that is given us.','我们要决定的，只有如何使用被给予的时间。','J.R.R. Tolkien, The Fellowship of the Ring']];
function renderDailyQuote(){const quote=dailyQuotes[new Date().getDay()];$('#daily-quote-cn').textContent=quote[0];$('#daily-quote-en').textContent=quote[1];$('#daily-quote-source').textContent=quote[2];}
function renderCalendar(){const year=calendarCursor.getFullYear(),month=calendarCursor.getMonth(),first=new Date(year,month,1),offset=(first.getDay()+6)%7,days=new Date(year,month+1,0).getDate();$('#calendar-title').textContent=new Intl.DateTimeFormat(language==='en'?'en-US':'zh-CN',{year:'numeric',month:'long'}).format(first);let cells=Array(offset).fill('<span class="calendar-day empty"></span>');for(let day=1;day<=days;day++){const key=localDateKey(new Date(year,month,day)),completed=state.completedSessions.find(item=>item.date===key),record=completed||state.restDays.includes(key)?completed||{session:'恢复日'}:null,isToday=key===today;cells.push(`<span class="calendar-day ${record?'has-record':''} ${isToday?'today':''}" title="${record?t(record.session):''}"><b>${day}</b>${record?`<i class="record ${record.session==='力量 A'?'strength-a':record.session==='力量 B'?'strength-b':record.session==='跑走耐力'?'run':'recovery'}">${typeLabel(record.session)}</i>`:''}</span>`);}$('#calendar-grid').innerHTML=cells.join('');const total=state.completedSessions.filter(item=>item.date.startsWith(`${year}-${String(month+1).padStart(2,'0')}`)).length,rests=state.restDays.filter(key=>key.startsWith(`${year}-${String(month+1).padStart(2,'0')}`)).length;$('#calendar-summary').textContent=t(total||rests?`本月已完成 ${total} 次训练，安排 ${rests} 天休息`:'本月从第一份训练开始。');renderDailyQuote();}
function render(){completeTodayIfReady();const current=sessions[state.session];$('#session-title').textContent=t(state.session);$('#session-summary').textContent=t(current.summary);$('#workout-list').innerHTML=current.exercises.map(([name,dose,videoId])=>englishMarkup(`<article class="exercise"><span><strong>${name}</strong><small>${dose}</small>${setButtons(name,dose)}</span><button class="video-link" data-video-id="${videoId}" data-video-title="${name}" data-motion="${motionType(name)}" aria-label="${language==='en'?`View ${t(name)} guide`:`查看 ${name} 图文指导`}" title="图文指导">▷</button></article>`)).join('');const done=state.completedSessions.some(item=>item.date===today),resting=state.restDays.includes(today);$('#complete-session').textContent=t(done?'今日已完成':resting?'今日休息':'完成今日训练');$('#complete-session').classList.toggle('completed',done||resting);$('#complete-session').disabled=resting;$('#rest-today').textContent=t(resting?'恢复今日训练':'今日休息');$('#rest-today').disabled=done;document.querySelectorAll('[data-readiness]').forEach(button=>button.classList.toggle('selected',button.dataset.readiness===state.readiness));renderCalendar();}
function wikiTerm(name){return {'高位俯卧撑':'俯卧撑','扶椅后撤箭步蹲':'箭步蹲','单腿臀桥':'臀桥','俯卧 Y-T 抬臂':'肩胛骨','墙面肩胛俯卧撑':'肩胛骨','慢速提踵':'提踵','踝关节活动':'踝关节','热身快走':'快走','放松慢走':'快走','轻松快走':'快走','跑走交替':'跑步'}[name]||name;}
function openVideo(button){const name=button.dataset.videoTitle,guide=guides[name]||{steps:['先用舒适范围开始，动作保持缓慢可控。','训练中持续呼吸，避免借力或追求极限幅度。','出现疼痛、不稳或麻木时停止并改为恢复训练。']},images=guide.images||[],steps=language==='en'?['Set up in a stable, comfortable position before you begin.','Move slowly and under control while breathing normally.','Stop and switch to recovery work if you feel pain, numbness, or instability.']:guide.steps;$('#video-title').textContent=`${t(name)} ${language==='en'?'guide':'指导'}`;$('#guide-images').innerHTML=images.map((src,index)=>`<img class="guide-image" src="${src}" alt="${t(name)} ${language==='en'?'movement illustration':'动作示意'} ${index+1}" loading="eager">`).join('');$('#guide-empty').textContent=images.length?'':t('暂无已核验的公开授权图片，请按下方三步要点完成。');$('#guide-steps').innerHTML=steps.map(step=>`<li>${t(step)}</li>`).join('');$('#wiki-link').href=language==='en'?`https://en.wikipedia.org/wiki/${encodeURIComponent(t(wikiTerm(name)).replace(/ /g,'_'))}`:`https://baike.baidu.com/item/${encodeURIComponent(wikiTerm(name))}`;$('#wiki-link').textContent=t('在百度百科查阅');$('#video-credit').textContent=images.length?t('图片：项目作者使用 AI 图像生成工具制作。'):'';$('#video-dialog').showModal();}
let activeFeedbackProfile;
function openFeedback(button){const name=button.dataset.feedbackExercise;activeFeedbackProfile=feedbackProfile(name);$('#feedback-dialog').dataset.exercise=name;$('#feedback-title').textContent=language==='en'?`${t(name)} check-in`:`${name}状态反馈`;$('#feedback-context').textContent=language==='en'?'Choose the option that best matches how the movement feels right now.':activeFeedbackProfile.context;$('#feedback-options').innerHTML=language==='en'?'<button data-feedback-kind="0"><strong>Muscle fatigue</strong><span>Working muscles feel tired or tight, without joint pain</span></button><button data-feedback-kind="1"><strong>Pain or instability</strong><span>Sharp pain, numbness, joint pain, or loss of control</span></button><button data-feedback-kind="2"><strong>Feeling steady</strong><span>You can keep moving with good control and normal breathing</span></button>':activeFeedbackProfile.options.map((option,index)=>`<button data-feedback-kind="${index}"><strong>${option[0]}</strong><span>${option[1]}</span></button>`).join('');$('#feedback-result').hidden=true;$('#feedback-options').hidden=false;$('#feedback-dialog').showModal();}
function showFeedbackResult(kind){const index=Number(kind),name=$('#feedback-dialog').dataset.exercise,shouldCap=index===0||(/深蹲|箭步|静蹲/.test(name)&&index===2);if(shouldCap){state.cappedExercises[setKey(name)]=activeFeedbackProfile.options[index][0];save();render();}$('#feedback-result').textContent=language==='en'?(index===1?'Stop this movement and switch to comfortable recovery work. Seek qualified help if symptoms persist, worsen, or affect daily activity.':index===0?'Rest briefly, then reduce the next set if needed. The movement is now marked at today\'s limit.':'Continue only while the movement stays controlled and comfortable.'):`${activeFeedbackProfile.options[index][2]}${shouldCap?' 已将本动作标为“已达上限”。':''}`;$('#feedback-options').hidden=true;$('#feedback-result').hidden=false;}
$('#readiness-options').addEventListener('click',event=>{if(!event.target.dataset.readiness)return;state.readiness=event.target.dataset.readiness;const messages={low:'今天降低训练量：改恢复日或每个动作少做一组。',normal:'按计划完成，所有动作保留 2 次余力。',high:'状态很好也不练到力竭。任选一个动作每组加 1 次。'};$('#status-copy').textContent=messages[state.readiness];save();render();});
$('#switch-session').onclick=()=>{const keys=Object.keys(sessions),index=keys.indexOf(state.session);state.session=keys[(index+1)%keys.length];save();render();};
let completionToastTimer;
function celebrateCompletion(){const button=$('#complete-session'),toast=$('#completion-toast');button.classList.add('celebrate');navigator.vibrate?.([20,45,35]);toast.classList.add('show');clearTimeout(completionToastTimer);completionToastTimer=setTimeout(()=>toast.classList.remove('show'),2200);}
$('#complete-session').onclick=()=>{if(state.completedSessions.some(item=>item.date===today)||state.restDays.includes(today))return;state.completedSessions.push({date:today,session:state.session});save();render();celebrateCompletion();};
$('#rest-today').onclick=()=>{if(state.restDays.includes(today)){state.restDays=state.restDays.filter(day=>day!==today);}else if(!state.completedSessions.some(item=>item.date===today)){state.restDays.push(today);}save();render();};
document.addEventListener('click',event=>{const button=event.target.closest('[data-video-id]');if(!button)return;event.preventDefault();event.stopPropagation();openVideo(button);});
document.addEventListener('click',event=>{const button=event.target.closest('[data-feedback-exercise]');if(!button)return;openFeedback(button);});
document.addEventListener('click',event=>{const button=event.target.closest('[data-rest-exercise]');if(!button)return;const name=button.dataset.restExercise;$('#rest-title').textContent=`${name}休息`;$('#rest-options').innerHTML=restParts(name).map(part=>`<button data-rest-part="${part}"><strong>${part}未恢复</strong><span>今天暂停本动作的剩余组数</span></button>`).join('');$('#rest-dialog').dataset.exercise=name;$('#rest-dialog').showModal();});
document.addEventListener('click',event=>{const button=event.target.closest('[data-complete-set]');if(!button)return;completeSet(button.dataset.completeSet,Number(button.dataset.setIndex),button.dataset.progressScope||'plan');render();navigator.vibrate?.(25);});
document.addEventListener('click',event=>{const button=event.target.closest('[data-undo-set]');if(!button)return;const scope=button.dataset.progressScope||'plan',name=button.dataset.undoSet,key=setKey(name,scope),index=Number(button.dataset.setIndex);state.setChecks[key]=checkedSets(name,scope).filter(item=>item!==index);save();render();});
document.addEventListener('click',event=>{const button=event.target.closest('[data-start-timer]');if(!button)return;const scope=button.dataset.progressScope||'plan',name=button.dataset.startTimer,index=Number(button.dataset.setIndex),seconds=Number(button.dataset.timerSeconds);state.activeTimers[timerKey(name,index,scope)]={name,index,scope,endsAt:Date.now()+seconds*1000};save();render();});
document.addEventListener('click',event=>{const button=event.target.closest('[data-cancel-timer]');if(!button)return;delete state.activeTimers[timerKey(button.dataset.cancelTimer,Number(button.dataset.setIndex),button.dataset.progressScope||'plan')];save();render();});
document.addEventListener('click',event=>{const button=event.target.closest('[data-resume-exercise]');if(!button)return;delete state.restedExercises[setKey(button.dataset.resumeExercise,button.dataset.progressScope||'plan')];save();render();});
document.addEventListener('click',event=>{const button=event.target.closest('[data-resume-cap]');if(!button)return;delete state.cappedExercises[setKey(button.dataset.resumeCap,button.dataset.progressScope||'plan')];save();render();});
$('#close-video').onclick=()=>{$('#guide-images').innerHTML='';$('#video-dialog').close();};
$('#feedback-options').addEventListener('click',event=>{const button=event.target.closest('[data-feedback-kind]');if(button)showFeedbackResult(button.dataset.feedbackKind);});
$('#rest-options').addEventListener('click',event=>{const button=event.target.closest('[data-rest-part]');if(!button)return;state.restedExercises[setKey($('#rest-dialog').dataset.exercise)]=button.dataset.restPart;save();$('#rest-dialog').close();render();});
$('#previous-month').onclick=()=>{calendarCursor=new Date(calendarCursor.getFullYear(),calendarCursor.getMonth()-1,1);renderCalendar();};
$('#next-month').onclick=()=>{calendarCursor=new Date(calendarCursor.getFullYear(),calendarCursor.getMonth()+1,1);renderCalendar();};
function showView(view){document.querySelectorAll('[data-view]').forEach(section=>{const active=section.dataset.view===view;section.hidden=!active;section.classList.toggle('is-active',active);});document.querySelectorAll('[data-nav-view]').forEach(button=>{const active=button.dataset.navView===view;button.classList.toggle('is-active',active);button.setAttribute('aria-selected',String(active));});localStorage.setItem('train-well-active-view',view);window.scrollTo({top:0,behavior:'auto'});}
document.querySelectorAll('[data-nav-view]').forEach(button=>button.addEventListener('click',()=>showView(button.dataset.navView)));
$('#today-date').textContent=new Intl.DateTimeFormat(language==='en'?'en-US':'zh-CN',{month:'long',day:'numeric',weekday:'short'}).format(new Date());prepareToday();render();showView(localStorage.getItem('train-well-active-view')||'today');localizePage();checkReminder();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');

function renderPlanPicker(){const picker=$('#plan-picker');if(!picker)return;picker.innerHTML=Object.entries(sessions).map(([name,session])=>englishMarkup(`<article class="plan-card ${name===state.session?'is-current':''}"><div><h2>${name}</h2><p>${session.summary}</p><p class="guide-group">${session.exercises.length} 个动作</p></div><button class="text-button" data-select-session="${name}">${name===state.session?'已选择':'选择'}</button></article>`)).join('');}
function renderRepairLibrary(){const library=$('#guide-library');if(!library)return;library.innerHTML=repairs.map(([name,dose,videoId])=>englishMarkup(`<article class="guide-card repair-card"><div><strong>${name}</strong><small>${dose}</small>${setButtons(name,dose,true,'repair')}</div><button class="video-link" data-video-id="${videoId}" data-video-title="${name}" data-motion="${motionType(name)}" aria-label="${language==='en'?`View ${t(name)} guide`:`查看 ${name} 图文指导`}" title="图文指导">▷</button></article>`)).join('');}
const baseRender=render;render=function(){baseRender();renderPlanPicker();renderRepairLibrary();};render();
document.addEventListener('click',event=>{const button=event.target.closest('[data-select-session]');if(!button)return;state.session=button.dataset.selectSession;save();render();showView('today');});
$('#settings-button').onclick=()=>showView('settings');
$('#language-toggle').onclick=()=>{localStorage.setItem(languageKey,language==='en'?'zh':'en');location.reload();};
$('#close-video').onclick=()=>$('#video-dialog').close();
$('#reminder-time').value=state.reminder||$('#reminder-time').value;
$('#save-settings').onclick=async()=>{state.reminder=$('#reminder-time').value;localStorage.removeItem(`train-well-reminded-${today}`);save();if('Notification'in window&&Notification.permission==='default')await Notification.requestPermission();checkReminder();const toast=$('#completion-toast');toast.textContent=t('设置已保存');toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1800);};
finishElapsedTimers();setInterval(()=>{if(Object.keys(state.activeTimers).length){finishElapsedTimers();render();}},500);setInterval(checkReminder,30000);document.addEventListener('visibilitychange',()=>{if(!document.hidden){finishElapsedTimers();checkReminder();}});window.addEventListener('focus',()=>{finishElapsedTimers();checkReminder();});
